[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "helyOS Developer Manual"
authors = [{name = "Jiapan Wang", email = "jiapan.wang@ivi.fraunhofer.de"}]
dynamic = ["version", "description"]
